In [231]:
import numpy as np
import pandas as pd

In [232]:
patients = pd.read_csv('patients.csv')
treatment = pd.read_csv('treatments.csv')
adverse_reactions = pd.read_csv('adverse_reactions.csv')

In [233]:
print(patients.shape)
print(treatment.shape)
print(adverse_reactions.shape)

(503, 14)
(280, 7)
(34, 3)


In [234]:
patients

patient_id assigned_sex given_name      surname  \
0             1       female        Zoe      Wellish   
1             2       female     Pamela         Hill   
2             3         male        Jae       Debord   
3             4         male       Liêm         Phan   
4             5         male        Tim      Neudorf   
..          ...          ...        ...          ...   
498         499         male    Mustafa    Lindström   
499         500         male      Ruman      Bisliev   
500         501       female      Jinke    de Keizer   
501         502       female    Chidalu  Onyekaozulu   
502         503         male        Pat      Gersten   

                       address               city       state  zip_code  \
0         576 Brown Bear Drive  Rancho California  California   92390.0   
1    2370 University Hill Road          Armstrong    Illinois   61812.0   
2        1493 Poling Farm Road               York    Nebraska   68467.0   
3          2335 Webster Street         Woodbridge          NJ    7095.0   
4         1428 Turkey Pen Lane             Dothan          AL   36303.0   
..                         ...                ...         ...       ...   
498        2530 Victoria Court       Milton Mills          ME    3852.0   
499   494 Clarksburg Park Road             Sedona          AZ   86341.0   
500          649 Nutter Street      Overland Park          MO   64110.0   
501   3652 Boone Crockett Lane            Seattle          WA   98109.0   
502          2778 North Avenue               Burr    Nebraska   68324.0   

           country                                          contact  \
0    United States             951-719-9170ZoeWellish@superrito.com   
1    United States            PamelaSHill@cuvox.de+1 (217) 569-3204   
2    United States                 402-363-6804JaeMDebord@gustr.com   
3    United States       PhanBaLiem@jourrapide.com+1 (732) 636-8246   
4    United States                  334-515-7487TimNeudorf@cuvox.de   
..             ...                                              ...   
498  United States      207-477-0579MustafaLindstrom@jourrapide.com   
499  United States               928-284-4492RumanBisliev@gustr.com   
500  United States            816-223-6007JinkedeKeizer@teleworm.us   
501  United States  ChidaluOnyekaozulu@jourrapide.com1 360 443 2060   
502  United States             PatrickGersten@rhyta.com402-848-4923   

     birthdate  weight  height   bmi  
0    7/10/1976   121.7      66  19.6  
1     4/3/1967   118.8      66  19.2  
2    2/19/1980   177.8      71  24.8  
3    7/26/1951   220.9      70  31.7  
4    2/18/1928   192.3      27  26.1  
..         ...     ...     ...   ...  
498  4/10/1959   181.1      72  24.6  
499  3/26/1948   239.6      70  34.4  
500  1/13/1971   171.2      67  26.8  
501  2/13/1952   176.9      67  27.7  
502   5/3/1954   138.2      71  19.3  

[503 rows x 14 columns]

In [235]:
treatment

given_name       surname    auralin    novodra  hba1c_start  hba1c_end  \
0     veronika      jindrová  41u - 48u          -         7.63       7.20   
1       elliot    richardson          -  40u - 45u         7.56       7.09   
2     yukitaka      takenaka          -  39u - 36u         7.68       7.25   
3         skye    gormanston  33u - 36u          -         7.97       7.62   
4       alissa        montez          -  33u - 29u         7.78       7.46   
..         ...           ...        ...        ...          ...        ...   
275     albina      zetticci  45u - 51u          -         7.93       7.73   
276       john   teichelmann          -  49u - 49u         7.90       7.58   
277     mathea       lillebø  23u - 36u          -         9.04       8.67   
278     vallie        prince  31u - 38u          -         7.64       7.28   
279     samúel  guðbrandsson  53u - 56u          -         8.00       7.64   

     hba1c_change  
0             NaN  
1            0.97  
2             NaN  
3            0.35  
4            0.32  
..            ...  
275          0.20  
276           NaN  
277          0.37  
278          0.36  
279          0.36  

[280 rows x 7 columns]

In [236]:
adverse_reactions

given_name     surname           adverse_reaction
0         berta  napolitani  injection site discomfort
1          lena        baer               hypoglycemia
2        joseph         day               hypoglycemia
3        flavia  fiorentino                      cough
4       manouck     wubbels          throat irritation
5       jasmine       sykes               hypoglycemia
6        louise     johnson               hypoglycemia
7       albinca     komavec               hypoglycemia
8           noe      aranda               hypoglycemia
9         sofia   hermansen  injection site discomfort
10        tegan     johnson                   headache
11         abel     yonatan                      cough
12    abdul-nur         isa               hypoglycemia
13         leon      scholz  injection site discomfort
14     gabriele     saenger               hypoglycemia
15       jia li        teng                     nausea
16        jakob    jakobsen               hypoglycemia
17  christopher    woodward                     nausea
18          ole    petersen               hypoglycemia
19       finley    chandler                   headache
20     anenechi       chidi               hypoglycemia
21     miłosław  wiśniewski  injection site discomfort
22        lixue       hsueh  injection site discomfort
23        merci      leroux               hypoglycemia
24         kang         mai  injection site discomfort
25       elliot  richardson               hypoglycemia
26      clinton      miller          throat irritation
27       idalia       moore               hypoglycemia
28       xiuxiu       chang               hypoglycemia
29         alex    crawford               hypoglycemia
30       monika      lončar               hypoglycemia
31       steven         roy                   headache
32      cecilie      nilsen               hypoglycemia
33    krisztina      magyar               hypoglycemia

In [237]:
# Programmatic assessment


In [238]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   patient_id    503 non-null    int64  
 1   assigned_sex  503 non-null    object 
 2   given_name    503 non-null    object 
 3   surname       503 non-null    object 
 4   address       491 non-null    object 
 5   city          491 non-null    object 
 6   state         491 non-null    object 
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object 
 9   contact       491 non-null    object 
 10  birthdate     503 non-null    object 
 11  weight        503 non-null    float64
 12  height        503 non-null    int64  
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB


In [239]:
patients[patients['address'].isnull()]

patient_id assigned_sex given_name      surname address city state  \
209         210       female     Lalita  Eldarkhanov     NaN  NaN   NaN   
219         220         male         Mỹ        Quynh     NaN  NaN   NaN   
230         231       female  Elisabeth      Knudsen     NaN  NaN   NaN   
234         235       female    Martina    Tománková     NaN  NaN   NaN   
242         243         male       John      O'Brian     NaN  NaN   NaN   
249         250         male   Benjamin       Mehler     NaN  NaN   NaN   
257         258         male        Jin         Kung     NaN  NaN   NaN   
264         265       female   Wafiyyah       Asfour     NaN  NaN   NaN   
269         270       female     Flavia   Fiorentino     NaN  NaN   NaN   
278         279       female   Generosa        Cabán     NaN  NaN   NaN   
286         287         male      Lewis         Webb     NaN  NaN   NaN   
296         297       female        Chỉ          Lâm     NaN  NaN   NaN   

     zip_code country contact   birthdate  weight  height   bmi  
209       NaN     NaN     NaN   8/14/1950   143.4      62  26.2  
219       NaN     NaN     NaN    4/9/1978   237.8      69  35.1  
230       NaN     NaN     NaN   9/23/1976   165.9      63  29.4  
234       NaN     NaN     NaN    4/7/1936   199.5      65  33.2  
242       NaN     NaN     NaN   2/25/1957   205.3      74  26.4  
249       NaN     NaN     NaN  10/30/1951   146.5      69  21.6  
257       NaN     NaN     NaN   5/17/1995   231.7      69  34.2  
264       NaN     NaN     NaN   11/3/1989   158.6      63  28.1  
269       NaN     NaN     NaN   10/9/1937   175.2      61  33.1  
278       NaN     NaN     NaN  12/16/1962   124.3      69  18.4  
286       NaN     NaN     NaN    4/1/1979   155.3      68  23.6  
296       NaN     NaN     NaN   5/14/1990   181.1      63  32.1

In [240]:
treatment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   given_name    280 non-null    object 
 1   surname       280 non-null    object 
 2   auralin       280 non-null    object 
 3   novodra       280 non-null    object 
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB


In [241]:
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 944.0+ bytes


In [242]:
patients.describe()

patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [243]:
treatment.describe()

hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [244]:
patients.sample(5)

patient_id assigned_sex given_name      surname              address  \
428         429         male      Marko          Kos   1128 Jacobs Street   
378         379       female     Furuta        Osman  3300 Woodridge Lane   
460         461         male       Arne    Jørgensen    1033 Wayside Lane   
262         263       female    Rebecca       Priest     2020 Gore Street   
209         210       female     Lalita  Eldarkhanov                  NaN   

           city state  zip_code        country  \
428  Pittsburgh    PA   15212.0  United States   
378     Memphis    TN   38115.0  United States   
460     Oakland    CA   94612.0  United States   
262     Houston    TX   77092.0  United States   
209         NaN   NaN       NaN            NaN   

                                       contact   birthdate  weight  height  \
428            412-319-0903MarkoKos@einrot.com  10/21/1982   227.7      69   
378        FurutaOsman@rhyta.com1 901 316 3780  11/28/1933   138.8      63   
460  ArneJrgensen@fleckens.hu+1 (510) 238-1151   3/14/1998   163.5      65   
262      713-556-4328RebeccaRPriest@dayrep.com   3/26/1988   194.0      68   
209                                        NaN   8/14/1950   143.4      62   

      bmi  
428  33.6  
378  24.6  
460  27.2  
262  29.5  
209  26.2

In [245]:
patients[patients['address'].duplicated()]

patient_id assigned_sex given_name     surname             address  \
29           30         male       Jake    Jakobsen   648 Old Dear Lane   
219         220         male         Mỹ       Quynh                 NaN   
229         230         male       John         Doe     123 Main Street   
230         231       female  Elisabeth     Knudsen                 NaN   
234         235       female    Martina   Tománková                 NaN   
237         238         male       John         Doe     123 Main Street   
242         243         male       John     O'Brian                 NaN   
244         245         male       John         Doe     123 Main Street   
249         250         male   Benjamin      Mehler                 NaN   
251         252         male       John         Doe     123 Main Street   
257         258         male        Jin        Kung                 NaN   
264         265       female   Wafiyyah      Asfour                 NaN   
269         270       female     Flavia  Fiorentino                 NaN   
277         278         male       John         Doe     123 Main Street   
278         279       female   Generosa       Cabán                 NaN   
282         283       female      Sandy      Taylor  2476 Fulton Street   
286         287         male      Lewis        Webb                 NaN   
296         297       female        Chỉ         Lâm                 NaN   
502         503         male        Pat     Gersten   2778 North Avenue   

            city     state  zip_code        country  \
29   Port Jervis  New York   12771.0  United States   
219          NaN       NaN       NaN            NaN   
229     New York        NY   12345.0  United States   
230          NaN       NaN       NaN            NaN   
234          NaN       NaN       NaN            NaN   
237     New York        NY   12345.0  United States   
242          NaN       NaN       NaN            NaN   
244     New York        NY   12345.0  United States   
249          NaN       NaN       NaN            NaN   
251     New York        NY   12345.0  United States   
257          NaN       NaN       NaN            NaN   
264          NaN       NaN       NaN            NaN   
269          NaN       NaN       NaN            NaN   
277     New York        NY   12345.0  United States   
278          NaN       NaN       NaN            NaN   
282     Rainelle        WV   25962.0  United States   
286          NaN       NaN       NaN            NaN   
296          NaN       NaN       NaN            NaN   
502         Burr  Nebraska   68324.0  United States   

                                        contact   birthdate  weight  height  \
29   JakobCJakobsen@einrot.com+1 (845) 858-7707    8/1/1985   155.8      67   
219                                         NaN    4/9/1978   237.8      69   
229                 johndoe@email.com1234567890    1/1/1975   180.0      72   
230                                         NaN   9/23/1976   165.9      63   
234                                         NaN    4/7/1936   199.5      65   
237                 johndoe@email.com1234567890    1/1/1975   180.0      72   
242                                         NaN   2/25/1957   205.3      74   
244                 johndoe@email.com1234567890    1/1/1975   180.0      72   
249                                         NaN  10/30/1951   146.5      69   
251                 johndoe@email.com1234567890    1/1/1975   180.0      72   
257                                         NaN   5/17/1995   231.7      69   
264                                         NaN   11/3/1989   158.6      63   
269                                         NaN   10/9/1937   175.2      61   
277                 johndoe@email.com1234567890    1/1/1975   180.0      72   
278                                         NaN  12/16/1962   124.3      69   
282        304-438-2648SandraCTaylor@dayrep.com  10/23/1960   206.1      64   
286                                         NaN    4/1/1979 

# Quality

In [246]:
# dimension = [Completeness, Validity, Accuracy, Consistent]

# ##'patients'
#     - zip code col are stored in decimal format [V] (done)
#     - certain zip codes are of 4 numbers [V] (not done yet)
#     - for state col sometimes it is full name of state of sometimes it is an abbreviation [IC] (not done yet)
#     - inconsistent way of storing phone numbers in contact col [IC]
#     - 12 missing values in contact col [C]  
#     - Incorrect data types for assigned_sex(should be category) and birthdate(should be in date format) [?] (done)
#     - Errornous data for height and weight [A]
#     - zip code col contains 491 rows (i.e having missing values) [C]-- (done)
#     - Duplicate and not useful data in dataset [IC] (done)


# ##'treatment'
#     - hba1c_change col contains missing values(nan values) [C] (done)
#     - In novodra and auralin col u is attached to numbers that makes the col string and can be a difficulty to perform mathematical operations on it.[V] (done)
#     - Only 280 rows are there, instead of 350. [C]
#     - Name and surname col is in lower case [IC] (done)
#     - Incorrect data types for aurilin and novodra cols [V] (done)
#     - hba1c_change col 9 instead of 4 [A] (done)
#     - use of dashes instead of nan in auralin and novodra cols [IC] (done)


# ##'adverse_reactions'
#      - Name and surname col is in lower case [IC] (done)

# Tidiness

patients
# phone and email together in one col

treatment
# 3 variables stored in auralin and novodra

adverse_reactions
# No point of using this table

# 

# Data Cleaning

In [247]:
# making copies
patients_copy = patients.copy()
treatment_copy = treatment.copy()
adverse_reactions_copy = adverse_reactions.copy()

# Completeness issues

- 12 missing values in contact col [C] (not possible)

- Only 280 rows are there, instead of 350. [C] 

- hba1c_change col contains missing values(nan values) [C]

- zip code col contains 491 rows (i.e having missing values) [C]

define

In [248]:
# Subtract hba1c_start from hba1c_end to get hba1c_change  

Code

In [249]:
treatment_copy['hba1c_change'] = treatment_copy['hba1c_start'] - treatment_copy['hba1c_end']

Test

In [250]:
treatment_copy['hba1c_change'].isnull().sum()

0

In [251]:
# treatment_copy.info()

treatment_copy.describe()

hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    280.000000
mean      7.985929    7.589286      0.396643
std       0.568638    0.569672      0.060168
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.350000
50%       7.800000    7.420000      0.390000
75%       7.970000    7.570000      0.440000
max       9.950000    9.580000      0.540000

2. define

In [252]:
# filling zip code col that contains 491 rows (i.e having missing values) by fillna

Code

In [253]:
patients_copy['zip_code']=patients_copy['zip_code'].fillna(method='bfill')

Test

In [254]:
patients_copy['zip_code'].isnull().sum()

0

In [255]:
patients_copy['zip_code']

0      92390.0
1      61812.0
2      68467.0
3       7095.0
4      36303.0
        ...   
498     3852.0
499    86341.0
500    64110.0
501    98109.0
502    68324.0
Name: zip_code, Length: 503, dtype: float64

# Tideness issues

- phone and email together in one col

- 3 variables stored in auralin and novodra

- No point of using this table

define

In [256]:
# novodra and auralin in using melt function


code

In [257]:
treatment_copy = pd.melt(treatment_copy, id_vars=['given_name', 'surname', 'hba1c_start', 'hba1c_end', 'hba1c_change'], 
                        var_name=['treatment'], value_name='dose')

In [258]:
treatment_copy = treatment_copy[treatment_copy['dose']!='-']

In [259]:
treatment_copy['start'], treatment_copy['end'] = treatment_copy['dose'].str.split('-').str

C:\Users\Hunani Trading Co\AppData\Local\Temp\ipykernel_9688\1689591346.py:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  treatment_copy['start'], treatment_copy['end'] = treatment_copy['dose'].str.split('-').str


In [260]:
treatment_copy.drop(columns={'dose'}, inplace=True)

Test

In [261]:
treatment_copy

given_name      surname  hba1c_start  hba1c_end  hba1c_change treatment  \
0     veronika     jindrová         7.63       7.20          0.43   auralin   
3         skye   gormanston         7.97       7.62          0.35   auralin   
6       sophia       haugen         7.65       7.27          0.38   auralin   
7        eddie       archer         7.89       7.55          0.34   auralin   
9         asia      woźniak         7.76       7.37          0.39   auralin   
..         ...          ...          ...        ...           ...       ...   
548     yasmin       araujo         7.82       7.36          0.46   novodra   
549     hiromu     horikawa         7.77       7.28          0.49   novodra   
551        leo       vieira         7.74       7.36          0.38   novodra   
552     steven          roy         7.87       7.43          0.44   novodra   
556       john  teichelmann         7.90       7.58          0.32   novodra   

    start   end  
0    41u    48u  
3    33u    36u  
6    37u    42u  
7    31u    38u  
9    30u    36u  
..    ...   ...  
548  51u    54u  
549  47u    46u  
551  30u    33u  
552  41u    43u  
556  49u    49u  

[280 rows x 8 columns]

define

In [262]:
#adding adverse table to treatment table by merge 

code

In [263]:
treatment_copy = treatment_copy.merge(adverse_reactions_copy)

In [264]:
treatment_copy

given_name     surname  hba1c_start  hba1c_end  hba1c_change treatment  \
0      joseph         day         7.70       7.19          0.51   auralin   
1      joseph         day         7.70       7.19          0.51   auralin   
2     clinton      miller         7.79       7.40          0.39   auralin   
3      louise     johnson         7.63       7.32          0.31   auralin   
4      finley    chandler         7.65       7.26          0.39   auralin   
5      idalia       moore         8.34       7.90          0.44   auralin   
6      xiuxiu       chang         7.64       7.23          0.41   auralin   
7    gabriele     saenger         8.35       7.97          0.38   auralin   
8       merci      leroux         8.98       8.64          0.34   auralin   
9    anenechi       chidi         7.64       7.31          0.33   auralin   
10    manouck     wubbels         7.66       7.40          0.26   auralin   
11     jia li        teng         7.66       7.32          0.34   auralin   
12       alex    crawford         7.69       7.30          0.39   auralin   
13     elliot  richardson         7.56       7.09          0.47   novodra   
14    jasmine       sykes         7.56       7.18          0.38   novodra   
15  krisztina      magyar         7.52       7.01          0.51   novodra   
16    albinca     komavec         7.89       7.46          0.43   novodra   
17        ole    petersen         7.95       7.55          0.40   novodra   
18  abdul-nur         isa         7.98       7.53          0.45   novodra   
19       abel     yonatan         7.88       7.50          0.38   novodra   
20      tegan     johnson         7.79       7.43          0.36   novodra   
21     monika      lončar         9.13       8.72          0.41   novodra   
22       lena        baer         7.70       7.40          0.30   novodra   
23    cecilie      nilsen         9.63       9.21          0.42   novodra   
24       kang         mai         7.78       7.45          0.33   novodra   
25       leon      scholz         7.72       7.29          0.43   novodra   
26     steven         roy         7.87       7.43          0.44   novodra   

   start   end           adverse_reaction  
0   29u    36u               hypoglycemia  
1   29u    36u               hypoglycemia  
2   42u    51u          throat irritation  
3   32u    42u               hypoglycemia  
4   31u    45u                   headache  
5   25u    31u               hypoglycemia  
6   32u    41u               hypoglycemia  
7   22u    30u               hypoglycemia  
8   27u    33u               hypoglycemia  
9   52u    61u               hypoglycemia  
10  55u    62u          throat irritation  
11  48u    54u                     nausea  
12  51u    62u               hypoglycemia  
13  40u    45u               hypoglycemia  
14  42u    44u               hypoglycemia  
15  32u    27u               hypoglycemia  
16  41u    39u               hypoglycemia  
17  29u    32u               hypoglycemia  
18  54u    50u               hypoglycemia  
19  38u    39u                      cough  
20  34u    34u                   headache  
21  49u    46u               hypoglycemia  
22  41u    38u               hypoglycemia  
23  49u    50u               hypoglycemia  
24  39u    36u  injection site discomfort  
25  38u    32u  injection site discomfort  
26  41u    43u                   headache

define

In [303]:
# splitting phone num and email from contact col by lambda and merge function

code

In [268]:
# patients_copy['contact']

In [269]:
# patients_copy['contact']=patients_copy['contact'].astype(str).str.extractall('(-\d+)').unstack().fillna('').sum(axis=1)

In [270]:
# patients_copy["contact"]


In [271]:
# patients_copy["contact"]=patients_copy["contact"].str.split('')

In [272]:
# patients_copy['contact'] = patients_copy['contact'].str.extract(r'([ab])?(\d)')
# patients_copy['contact']

# cleaning other issues

Define

In [273]:
#  converting zip code col from decimal format to int

code

In [274]:
patients_copy['zip_code'] = patients_copy['zip_code'].astype('int')


Test

In [275]:
patients_copy['zip_code']

0      92390
1      61812
2      68467
3       7095
4      36303
       ...  
498     3852
499    86341
500    64110
501    98109
502    68324
Name: zip_code, Length: 503, dtype: int32

Define

In [306]:
# changing state col to abbreviation form

Code

In [307]:
patients_copy['state'] = patients_copy['state'].str.extract('([A-Z\s]+)', expand=False).str.strip()

Test

In [308]:
patients_copy['state']

0       C
1       I
2       N
3      NJ
4      AL
       ..
498    ME
499    AZ
500    MO
501    WA
502     N
Name: state, Length: 503, dtype: object

2. Define

In [276]:
# converting datatype for assigned_sex( to category)

Code

In [277]:
patients_copy['assigned_sex'] = patients_copy['assigned_sex'].astype('category')

Test

In [278]:
patients_copy['assigned_sex'].astype

<bound method NDFrame.astype of 0      female
1      female
2        male
3        male
4        male
        ...  
498      male
499      male
500    female
501    female
502      male
Name: assigned_sex, Length: 503, dtype: category
Categories (2, object): ['female', 'male']>

3. Define

In [279]:
# converting data type for birthdate to date format

Code

In [280]:
patients_copy['birthdate'] = patients_copy['birthdate'].astype('datetime64')

Test

In [281]:
patients_copy['birthdate'].astype

<bound method NDFrame.astype of 0     1976-07-10
1     1967-04-03
2     1980-02-19
3     1951-07-26
4     1928-02-18
         ...    
498   1959-04-10
499   1948-03-26
500   1971-01-13
501   1952-02-13
502   1954-05-03
Name: birthdate, Length: 503, dtype: datetime64[ns]>

4. Define

In [282]:
# deleting duplicates

Code

In [283]:
patients_copy = patients_copy.drop_duplicates()

Test

In [284]:
patients_copy.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
498    False
499    False
500    False
501    False
502    False
Length: 503, dtype: bool

In [310]:
patients_copy.info


<bound method DataFrame.info of      patient_id assigned_sex given_name      surname  \
0             1       female        Zoe      Wellish   
1             2       female     Pamela         Hill   
2             3         male        Jae       Debord   
3             4         male       Liêm         Phan   
4             5         male        Tim      Neudorf   
..          ...          ...        ...          ...   
498         499         male    Mustafa    Lindström   
499         500         male      Ruman      Bisliev   
500         501       female      Jinke    de Keizer   
501         502       female    Chidalu  Onyekaozulu   
502         503         male        Pat      Gersten   

                       address               city state  zip_code  \
0         576 Brown Bear Drive  Rancho California     C     92390   
1    2370 University Hill Road          Armstrong     I     61812   
2        1493 Poling Farm Road               York     N     68467   
3          2335 Web

5. define

In [285]:
# converting Name and surname col in lower case [IC]

Code

In [286]:
treatment_copy['given_name'] = treatment_copy['given_name'].str.capitalize()

In [287]:
treatment_copy['surname'] = treatment_copy['surname'].str.capitalize()

Test

In [288]:
treatment_copy[['given_name', 'surname']]

given_name     surname
0      Joseph         Day
1      Joseph         Day
2     Clinton      Miller
3      Louise     Johnson
4      Finley    Chandler
5      Idalia       Moore
6      Xiuxiu       Chang
7    Gabriele     Saenger
8       Merci      Leroux
9    Anenechi       Chidi
10    Manouck     Wubbels
11     Jia li        Teng
12       Alex    Crawford
13     Elliot  Richardson
14    Jasmine       Sykes
15  Krisztina      Magyar
16    Albinca     Komavec
17        Ole    Petersen
18  Abdul-nur         Isa
19       Abel     Yonatan
20      Tegan     Johnson
21     Monika      Lončar
22       Lena        Baer
23    Cecilie      Nilsen
24       Kang         Mai
25       Leon      Scholz
26     Steven         Roy

7. Define

In [289]:
#removing u from start converting it to int

Code

In [290]:
treatment_copy['start']=treatment_copy['start'].astype(str).str.extractall('(\d+)').unstack().fillna('').sum(axis=1)

In [291]:
treatment_copy['start'] = treatment_copy['start'].astype(int)

Test

In [292]:
treatment_copy['start']

0     29
1     29
2     42
3     32
4     31
5     25
6     32
7     22
8     27
9     52
10    55
11    48
12    51
13    40
14    42
15    32
16    41
17    29
18    54
19    38
20    34
21    49
22    41
23    49
24    39
25    38
26    41
Name: start, dtype: int32

8. Define

In [293]:
#removing u from end converting it to int

Code

In [294]:
treatment_copy['end']=treatment_copy['end'].astype(str).str.extractall('(\d+)').unstack().fillna('').sum(axis=1)

In [295]:
treatment_copy['end'] = treatment_copy['end'].astype(int)

Test

In [296]:
treatment_copy['end']

0     36
1     36
2     51
3     42
4     45
5     31
6     41
7     30
8     33
9     61
10    62
11    54
12    62
13    45
14    44
15    27
16    39
17    32
18    50
19    39
20    34
21    46
22    38
23    50
24    36
25    32
26    43
Name: end, dtype: int32

9. Define

In [297]:
# convertig name col in upper case [IC]

In [298]:
adverse_reactions_copy['given_name'] = adverse_reactions_copy['given_name'].str.capitalize()

Test

In [299]:
adverse_reactions_copy['given_name']

0           Berta
1            Lena
2          Joseph
3          Flavia
4         Manouck
5         Jasmine
6          Louise
7         Albinca
8             Noe
9           Sofia
10          Tegan
11           Abel
12      Abdul-nur
13           Leon
14       Gabriele
15         Jia li
16          Jakob
17    Christopher
18            Ole
19         Finley
20       Anenechi
21       Miłosław
22          Lixue
23          Merci
24           Kang
25         Elliot
26        Clinton
27         Idalia
28         Xiuxiu
29           Alex
30         Monika
31         Steven
32        Cecilie
33      Krisztina
Name: given_name, dtype: object

10. Define

In [300]:
# converting surname in upper case

Code

In [301]:
adverse_reactions_copy['surname'] = adverse_reactions_copy['surname'].str.capitalize()

Test

In [302]:
adverse_reactions_copy['surname']

0     Napolitani
1           Baer
2            Day
3     Fiorentino
4        Wubbels
5          Sykes
6        Johnson
7        Komavec
8         Aranda
9      Hermansen
10       Johnson
11       Yonatan
12           Isa
13        Scholz
14       Saenger
15          Teng
16      Jakobsen
17      Woodward
18      Petersen
19      Chandler
20         Chidi
21    Wiśniewski
22         Hsueh
23        Leroux
24           Mai
25    Richardson
26        Miller
27         Moore
28         Chang
29      Crawford
30        Lončar
31           Roy
32        Nilsen
33        Magyar
Name: surname, dtype: object